# Generated by Django 3.0.6 on 2020-05-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fk_tag',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
