# Generated by Django 3.0.6 on 2020-05-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200519_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/static/images/post_default.png', upload_to='blog/static/images', verbose_name='Фото'),
        ),
    ]
